<?php

$navLinks	 = array();
$aTemplate = '<a %s href="%s">%s</a>';
$navFirst  = true;

$count = is_array($this->nav) ? count($this->nav) : 0;

for($i=0; $i<$count; $i++){
    $navItem  = $this->nav[$i];
    $aClass   = '';

    // <a> class
    if($navItem['is_selected']){
      $aClass = 'class="current"';
    }

    $navLinks[] = sprintf($aTemplate,$aClass,htmlentities($navItem['url'], ENT_QUOTES, 'UTF-8'),htmlentities($navItem['label'], ENT_QUOTES, 'UTF-8'));
}

// echo sprintf('%s',implode('<span>.</span>',$navLinks));
echo sprintf('%s',implode('<span></span>',$navLinks));
?>